language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install coveralls

services:
  - redis-server
  - mongodb
  - rabbitmq

script:
  coverage run --source=anypubsub setup.py test

after_success:
  coveralls
